version: "3.2"

services:
  superman:
    container_name: superman
    build: ./heroesapp
    image: heroesapp:latest
    command: node app.js
    environment:
      - NAME=Superman
    # ports:
    #   - "5001:5000"
    networks:
      - heroes

  deadpool:
    container_name: deadpool
    image: heroesapp:latest
    command: node app.js
    environment:
      - NAME=Deadpool
    depends_on:
      - superman
    # ports:
    #   - "5002:5000"
    networks:
      - heroes

  www:
    container_name: www
    build: ./loadbalancer
    image: heroesloadbalancer:latest
    ports:
      - "3000:8080"
    depends_on:
      - superman
      - deadpool
    networks:
      - heroes

networks:
  heroes: